spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/certmanagement
    username: sa         # ✅ Đổi thành user của bạn
    password: 123123    # ✅ Đổi thành password của bạn
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh



server:
  port: 8080
