spring:
  application:
    name: demo
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "khongmanhphuc2003@gmail.com"
    password: "zrml hcle xogz qfxe"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  app:
    jwtSecret: oWgZyJ5nQh4Kg7LqRJryMz6IlAV2c3XWkNF9s7xIEGo=
    jwtExpirationMs: 86400000

  datasource:
    url: jdbc:postgresql://localhost:5432/farmovo
    username: admin
    password: 123123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
aws:
  access-key-id: AKIAZ7OLKUTVXKNKW4W7
  secret-access-key: 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
  region: eu-north-1
  s3:
    bucket: my-debt-images

server:
  port: 8080