spring:
  application:
    name: demo
  app:
    jwtSecret: oWgZyJ5nQh4Kg7LqRJryMz6IlAV2c3XWkNF9s7xIEGo=
    jwtExpirationMs: 86400000  # 1 ngày

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: 123123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

server:
  port: 8080

