# Azure Docker Configuration
spring:
  profiles:
    include: azure
  
  # Override for Docker environment
  datasource:
    # Use environment variables for Docker
    url: ${AZURE_DB_URL:jdbc:postgresql://farmovo-postgres.postgres.database.azure.com:5432/farmovo}
    username: ${AZURE_DB_USERNAME:farmovo@farmovo-postgres}
    password: ${AZURE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# Docker-specific server settings
server:
  port: ${PORT:8080}
  # Docker health check endpoint
  servlet:
    context-path: /api

# Docker logging
logging:
  level:
    root: INFO
    com.farmovo.backend: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
