name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: |
          rm -rf dist
          npm run build
          # Xóa file không cần thiết
          find dist -name "*.map" -type f -delete
          find dist -name "*.DS_Store" -type f -delete
          find dist -type f -size +5M -delete  # xóa file >5MB (nếu có)

      - name: Check build size
        working-directory: frontend
        run: |
          echo "Build size analysis:"
          du -sh dist/
          echo "Number of files:"
          find dist -type f | wc -l
          echo "Largest files:"
          find dist -type f -exec ls -lh {} \; | sort -k5 -hr | head -10

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend"
          output_location: "dist"
          skip_app_build: true
