name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js + cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # 4. Build frontend & cleanup
      - name: Build and optimize
        working-directory: frontend
        run: |
          rm -rf dist
          npm run build
          # Xóa sourcemaps để giảm số lượng file
          find dist -name "*.map" -type f -delete
          # Xóa test files (nếu có)
          find dist -name "*.test.*" -type f -delete
          # Xóa file lớn để giảm kích thước
          find dist -type f -size +1M -delete
          # Xóa file không cần thiết
          find dist -name "*.DS_Store" -type f -delete
          find dist -name "*.log" -type f -delete
          # Xóa empty directories
          find dist -type d -empty -delete

      # 5. Check build size (debug nếu cần)
      - name: Check build size
        working-directory: frontend
        run: |
          echo "Build size analysis:"
          du -sh dist/
          echo "Number of files:"
          find dist -type f | wc -l
          echo "Largest files:"
          find dist -type f -exec ls -lh {} \; | sort -k5 -hr | head -10

      # 6. Deploy to Azure
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@main
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend"
          output_location: "dist"
          skip_app_build: true
