name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js + cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # 3.1. Optimize API dependencies (if exists)
      - name: Optimize API dependencies
        working-directory: api
        run: |
          if [ -f "package.json" ]; then
            echo "Optimizing API dependencies..."
            npm install --production
            # Xóa dev dependencies
            rm -rf node_modules/.cache
            rm -rf node_modules/.bin
            # Xóa source maps và test files
            find . -name "*.map" -type f -delete
            find . -name "*.test.*" -type f -delete
            echo "API size after optimization:"
            du -sh .
          else
            echo "No API directory found, skipping..."
          fi

      # 4. Build frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # 5. Optimize dist
      - name: Cleanup dist
        working-directory: frontend
        run: |
          echo "Removing unnecessary files..."
          find dist -name "*.map" -type f -delete
          find dist -name "*.test.*" -type f -delete
          find dist -type f -size +1M -delete
          find dist -name "*.chunk.*" -type f -delete
          find dist -name "*.DS_Store" -type f -delete
          find dist -name "*.log" -type f -delete
          # Xóa empty directories
          find dist -type d -empty -delete
          # Xóa file có hash dài
          find dist -name "*[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]*" -type f -delete

      # 6. Check build size
      - name: Check build size
        working-directory: frontend
        run: |
          echo "Frontend build size:"
          du -sh dist/
          echo "Number of files:"
          find dist -type f | wc -l
          echo "Largest files:"
          find dist -type f -exec ls -lh {} \; | sort -k5 -hr | head -10
          
          # Nếu quá nhiều file, zip lại
          if [ $(find dist -type f | wc -l) -gt 500 ]; then
            echo "Too many files, creating zip archive..."
            zip -r dist.zip dist/
            rm -rf dist/
            mkdir dist
            mv dist.zip dist/
          fi

      # 6.1. Check API size (if exists)
      - name: Check API size
        working-directory: api
        run: |
          if [ -d "." ]; then
            echo "API directory size:"
            du -sh .
            echo "API node_modules size:"
            if [ -d "node_modules" ]; then
              du -sh node_modules/
            else
              echo "No node_modules found"
            fi
          else
            echo "No API directory found"
          fi

      # 7. Deploy to Azure SWA
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend"
          output_location: "dist"
          skip_app_build: true
          action: "upload"
