name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # 3.5. Install ImageMagick for image optimization
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      # 4. Build frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # 5. Cleanup dist to reduce number of files
      - name: Optimize dist folder
        working-directory: frontend
        run: |
          # Xóa sourcemaps
          find dist -name "*.map" -type f -delete
          # Xóa test files
          find dist -name "*.test.*" -type f -delete
          # Xóa các chunk JS/CSS không cần thiết
          find dist -name "*.chunk.*" -type f -delete
          # Xóa file >2MB
          find dist -type f -size +2M -delete
          # Nén ảnh (PNG/JPG/WebP)
          find dist -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.webp" \) -exec mogrify -resize 50% {} \;

      # 6. Debug build size (số file & dung lượng)
      - name: Check build size
        working-directory: frontend
        run: |
          echo "Build size analysis:"
          du -sh dist/
          echo "Number of files:"
          find dist -type f | wc -l
          echo "Largest files:"
          find dist -type f -exec ls -lh {} \; | sort -k5 -hr | head -10

      # 7. Deploy to Azure SWA
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend"
          output_location: "dist"
          skip_app_build: true
          action: "upload"
