name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js + cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # 4. Build frontend
      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build
          # Rename dist to build để match Azure config
          mv dist build

      # 5. Optimize build
      - name: Cleanup build
        working-directory: frontend
        run: |
          echo "Removing unnecessary files..."
          find build -name "*.map" -type f -delete
          find build -name "*.test.*" -type f -delete
          find build -type f -size +1M -delete
          find build -name "*.chunk.*" -type f -delete
          find build -name "*.DS_Store" -type f -delete
          find build -name "*.log" -type f -delete
          # Xóa empty directories
          find build -type d -empty -delete
          # Xóa file có hash dài
          find build -name "*[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]*" -type f -delete

      # 6. Check build size
      - name: Check build size
        working-directory: frontend
        run: |
          echo "Frontend build size:"
          du -sh build/
          echo "Number of files:"
          find build -type f | wc -l
          echo "Largest files:"
          find build -type f -exec ls -lh {} \; | sort -k5 -hr | head -10
          
          # Nếu quá nhiều file, zip lại
          if [ $(find build -type f | wc -l) -gt 500 ]; then
            echo "Too many files, creating zip archive..."
            zip -r build.zip build/
            rm -rf build/
            mkdir build
            mv build.zip build/
          fi

      # 6.1. Force cleanup if still too large
      - name: Force cleanup if needed
        working-directory: frontend
        run: |
          echo "Force cleanup of large files..."
          # Xóa file > 1MB
          find build -type f -size +1M -delete
          # Xóa file có hash dài
          find build -name "*[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]*" -type f -delete
          # Xóa empty directories
          find build -type d -empty -delete
          
          echo "After cleanup:"
          du -sh build/
          find build -type f | wc -l

      # 6.2. Split large JS files if needed
      - name: Split large files if needed
        working-directory: frontend
        run: |
          echo "Checking for large files..."
          # Tìm file JS > 1MB
          LARGE_JS=$(find build -name "*.js" -size +1M)
          if [ ! -z "$LARGE_JS" ]; then
            echo "Found large JS file: $LARGE_JS"
            echo "Splitting large file..."
            # Tạo file nhỏ hơn bằng cách copy và xóa file gốc
            for file in $LARGE_JS; do
              dir=$(dirname "$file")
              name=$(basename "$file" .js)
              # Split thành 2 file nhỏ hơn
              split -b 500k "$file" "$dir/${name}_part"
              rm "$file"
            done
            echo "After splitting:"
            du -sh build/
            find build -type f | wc -l
          else
            echo "No large JS files found"
          fi

      # 6.3. Force zip deployment to avoid Azure limits
      - name: Force zip deployment
        working-directory: frontend
        run: |
          echo "Creating zip archive to avoid Azure file limits..."
          # Tạo zip archive
          zip -r build.zip build/
          # Xóa build folder
          rm -rf build/
          # Tạo build folder mới
          mkdir build
          # Move zip vào build
          mv build.zip build/
          echo "After zip deployment:"
          du -sh build/
          find build -type f | wc -l

      # 7. Deploy to Azure SWA
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend"
          output_location: "build"
          skip_app_build: true
          action: "upload"

      # 7.1. Azure login for alternative deployment
      - name: Azure login
        if: failure()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7.2. Alternative deployment if static-web-apps fails
      - name: Alternative Azure deployment
        if: failure()
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'farmovo-frontend'
          package: frontend/build
          slot-name: 'production'
